### ISSUE TITLE
k8s: podsecuritypolicy via OPA

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/rego-policies#129]
Can we OPA'erize:
- https://github.com/tektoncd/triggers/blob/master/config/101-podsecuritypolicy.yaml

This would probably need to be tested on vanilla k8s or on OCP with SCCs least enforcing, just to stop them interfering - needs a quick check.

**Comment by ckavili** [comment]
(just came to like '_OPA'erize_' 🙈)

**Comment by garethahealy** [comment]
@truncj ; hey, saw you mentioned you might pick this up on the CoP call agenda. Any progress / luck in getting time?

**Comment by garethahealy** [comment]
stale, didn't get any time/traction.
