### ISSUE TITLE
Publish policies to ArtifactHub

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/rego-policies#18]
Once we finalize some of the initial version of our policies, we should look to set up automation to start publishing them to [ArtifactHub](https://artifacthub.io)

**Comment by tylerauerbeck** [comment]
Looks like this part of the control plane isn't quite ready yet. Revisit this in the future.

**Comment by garethahealy** [comment]
Also, to use `conftest push`, it needs to conform to OCI spec which looking at the below, is hardly any:
- https://conformance.opencontainers.org/distribution-spec/

**Comment by garethahealy** [comment]
https://github.com/artifacthub/hub/issues/554

**Comment by garethahealy** [comment]
Testing on their staging env: https://staging.artifacthub.io/packages/opa/redhat-cop-rego-policies/redhat-cop-rego-policies

**Comment by garethahealy** [comment]
single repo vs multi repo in artifacthub? Anyone got any thoughts?

**Comment by ckavili** [comment]
I'd say single repo; the folder structure is good enough to follow 👀

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/rego-policies/blob/main/policy/artifacthub.yaml
