### ISSUE TITLE
Create governance Policy 🧽

### ISSUE THREAD

**Issue by springdo** [redhat-cop/rego-policies#23]
I started working on creating a rego policy for this - https://learnk8s.io/production-best-practices#governance

As I know lots of people are looking at this stuff now, to avoid duplicated effort lets capture some issues for policies we think could be good to write. I've started with this one

FYI
@ckavili @noelo @garethahealy @jtudelag

**Comment by garethahealy** [comment]
Have split out all those rules which could be applied to OCP into issues.

**Comment by garethahealy** [comment]
@springdo ; do you think there are any policies in your link that I've missed? if not, we ok to close this and track the policies via the raised issues?
