### ISSUE TITLE
🦇 move to cop-action once pr is merged 

### ISSUE THREAD

**Issue by springdo** [redhat-cop/rego-policies#25]
track the github-actions repo for conftestbats so we don't need to use @garethahealy 's dodgy repo/branch

**Comment by garethahealy** [comment]
PRs required before moving back to main:
- https://github.com/redhat-cop/github-actions/pull/15
- https://github.com/redhat-cop/github-actions/pull/14

**Comment by tylerauerbeck** [comment]
@garethahealy @springdo These two have been merged.

**Comment by springdo** [comment]
closing as @garethahealy has updated the action here
