### ISSUE TITLE
🙈 tidy up the policies to get greater reuse across modules 🙈 

### ISSUE THREAD

**Issue by springdo** [redhat-cop/rego-policies#31]
Each warn has four lines repeated, let's consider turning them into some kinda util or loaded thing. Could do it as a function too. 

https://www.openpolicyagent.org/docs/latest/policy-language/#imports

https://github.com/redhat-cop/rego-policies/pull/30

FYI @garethahealy

**Comment by garethahealy** [comment]
This has been somewhat done by the linked PRs but will be continued via: https://github.com/redhat-cop/rego-policies/issues/67

Closing since #67 can track future bits.
