### ISSUE TITLE
📣 base image warning from podman - needs to be more configurable ie no hardcode sha

### ISSUE THREAD

**Issue by springdo** [redhat-cop/rego-policies#35]
current tests are looking for a given sha to be in the imaga layer history. This policy is a great start but to be super useful across multiple projects, it would be better if we could pass in the SHA's to check against. 
   
https://github.com/redhat-cop/rego-policies/pull/33

FYI 
@garethahealy @noelo

**Comment by springdo** [comment]
https://github.com/redhat-cop/rego-policies/pull/34/files

**Comment by garethahealy** [comment]
The current thought process for this policy is to extend it so that it can look up the expected SHA, either by using the HTTP module or by providing expected metadata JSON alongside the `podman history`.

Whatever way we go, this policy will always need input from the company executing.
