### ISSUE TITLE
Enforce uniqueness in Ingress hostnames

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/rego-policies#59]
Parent: https://github.com/redhat-cop/rego-policies/issues/23
Suggestion: https://learnk8s.io/production-best-practices#application-development
Solved By: TODO

**Comment by jtudelag** [comment]
Just to clarify, this is for route objects (OCP Native) or for Ingess objects (k8s native)?

OCP 3.X enforces by default the uniqueness of route hostnames. That could be changed in OCP 3.X at router level:
https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#disable-namespace-ownership-check

OCP 4.X does the same. It can be changed, but at route level:
https://docs.openshift.com/container-platform/4.4/networking/routes/route-configuration.html#nw-route-admission-policy_route-configuration

**Comment by garethahealy** [comment]
@jtudelag ; Since Ingress creates Routes in OCP, I don't think it matters. But, if it's not applicable to OCP; it can be closed.
