### ISSUE TITLE
Understand the difference between the different root level methods

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/rego-policies#68]
We currently have:

- deny
- warn

But there's also 'violation'. I've googled but can't find a link that explains the different root level "types" and when/why you'd use them.

If anyone finds a link, please share.

**Comment by garethahealy** [comment]
@tylerauerbeck @springdo ; seen anything on your googling?

**Comment by garethahealy** [comment]
CC @ckavili

**Comment by ckavili** [comment]
It seems they changed the naming in gatekeeper last year: https://github.com/open-policy-agent/gatekeeper/issues/168

**Comment by garethahealy** [comment]
Ahhh. Didn't know that. So there are 3 rules:
- allow
- warn
- violation

**Comment by ckavili** [comment]
I’m not sure but if we are going to use Gatekeeper and [constraint templates](https://github.com/open-policy-agent/frameworks/tree/master/constraint#opa-constraint-framework), we need to go with violation but in the sense of using/testing policies with conftest, deny and violation seem to have no difference. At least not documented 🤷

**Comment by garethahealy** [comment]
Further reading, gatekeeper only supports `violation` which also adds another reason to make packages unique:
- https://github.com/redhat-cop/rego-policies/issues/71
